import json
import currencies as c
import requests

APIresponse = {'data': [{'type': 'flight-destination', 'origin': 'BOS', 'destination': 'PHL', 'departureDate': '2020-05-21', 'returnDate': '2020-05-31', 'price': {'total': '136.60'}, 'links': {'flightDates': 'https://test.api.amadeus.com/v1/shopping/flight-dates?origin=BOS&destination=PHL&departureDate=2020-05-21&oneWay=false&duration=10&nonStop=false&maxPrice=1000&currency=USD&viewBy=DURATION', 'flightOffers': 'https://test.api.amadeus.com/v2/shopping/flight-offers?originLocationCode=BOS&destinationLocationCode=PHL&departureDate=2020-05-21&returnDate=2020-05-31&adults=1&nonStop=false&maxPrice=1000&currency=USD'}},
          {'type': 'flight-destination', 'origin': 'BOS', 'destination': 'YTO', 'departureDate': '2020-05-21', 'returnDate': '2020-05-31', 'price': {'total': '279.30'}, 'links': {'flightDates': 'https://test.api.amadeus.com/v1/shopping/flight-dates?origin=BOS&destination=YTO&departureDate=2020-05-21&oneWay=false&duration=10&nonStop=false&maxPrice=1000&currency=USD&viewBy=DURATION', 'flightOffers': 'https://test.api.amadeus.com/v2/shopping/flight-offers?originLocationCode=BOS&destinationLocationCode=YTO&departureDate=2020-05-21&returnDate=2020-05-31&adults=1&nonStop=false&maxPrice=1000&currency=USD'}},
          {'type': 'flight-destination', 'origin': 'BOS', 'destination': 'BDA', 'departureDate': '2020-05-21', 'returnDate': '2020-05-31', 'price': {'total': '351.29'}, 'links': {'flightDates': 'https://test.api.amadeus.com/v1/shopping/flight-dates?origin=BOS&destination=BDA&departureDate=2020-05-21&oneWay=false&duration=10&nonStop=false&maxPrice=1000&currency=USD&viewBy=DURATION', 'flightOffers': 'https://test.api.amadeus.com/v2/shopping/flight-offers?originLocationCode=BOS&destinationLocationCode=BDA&departureDate=2020-05-21&returnDate=2020-05-31&adults=1&nonStop=false&maxPrice=1000&currency=USD'}},
          {'type': 'flight-destination', 'origin': 'BOS', 'destination': 'NAS', 'departureDate': '2020-05-21', 'returnDate': '2020-05-31', 'price': {'total': '376.23'}, 'links': {'flightDates': 'https://test.api.amadeus.com/v1/shopping/flight-dates?origin=BOS&destination=NAS&departureDate=2020-05-21&oneWay=false&duration=10&nonStop=false&maxPrice=1000&currency=USD&viewBy=DURATION', 'flightOffers': 'https://test.api.amadeus.com/v2/shopping/flight-offers?originLocationCode=BOS&destinationLocationCode=NAS&departureDate=2020-05-21&returnDate=2020-05-31&adults=1&nonStop=false&maxPrice=1000&currency=USD'}},
          {'type': 'flight-destination', 'origin': 'BOS', 'destination': 'GND', 'departureDate': '2020-05-21', 'returnDate': '2020-05-31', 'price': {'total': '440.96'}, 'links': {'flightDates': 'https://test.api.amadeus.com/v1/shopping/flight-dates?origin=BOS&destination=GND&departureDate=2020-05-21&oneWay=false&duration=10&nonStop=false&maxPrice=1000&currency=USD&viewBy=DURATION', 'flightOffers': 'https://test.api.amadeus.com/v2/shopping/flight-offers?originLocationCode=BOS&destinationLocationCode=GND&departureDate=2020-05-21&returnDate=2020-05-31&adults=1&nonStop=false&maxPrice=1000&currency=USD'}},
          {'type': 'flight-destination', 'origin': 'BOS', 'destination': 'BZE', 'departureDate': '2020-05-21', 'returnDate': '2020-05-31', 'price': {'total': '488.13'}, 'links': {'flightDates': 'https://test.api.amadeus.com/v1/shopping/flight-dates?origin=BOS&destination=BZE&departureDate=2020-05-21&oneWay=false&duration=10&nonStop=false&maxPrice=1000&currency=USD&viewBy=DURATION', 'flightOffers': 'https://test.api.amadeus.com/v2/shopping/flight-offers?originLocationCode=BOS&destinationLocationCode=BZE&departureDate=2020-05-21&returnDate=2020-05-31&adults=1&nonStop=false&maxPrice=1000&currency=USD'}},
          {'type': 'flight-destination', 'origin': 'BOS', 'destination': 'PTY', 'departureDate': '2020-05-21', 'returnDate': '2020-05-31', 'price': {'total': '523.13'}, 'links': {'flightDates': 'https://test.api.amadeus.com/v1/shopping/flight-dates?origin=BOS&destination=PTY&departureDate=2020-05-21&oneWay=false&duration=10&nonStop=false&maxPrice=1000&currency=USD&viewBy=DURATION', 'flightOffers': 'https://test.api.amadeus.com/v2/shopping/flight-offers?originLocationCode=BOS&destinationLocationCode=PTY&departureDate=2020-05-21&returnDate=2020-05-31&adults=1&nonStop=false&maxPrice=1000&currency=USD'}},
          {'type': 'flight-destination', 'origin': 'BOS', 'destination': 'SAL', 'departureDate': '2020-05-21', 'returnDate': '2020-05-31', 'price': {'total': '554.66'}, 'links': {'flightDates': 'https://test.api.amadeus.com/v1/shopping/flight-dates?origin=BOS&destination=SAL&departureDate=2020-05-21&oneWay=false&duration=10&nonStop=false&maxPrice=1000&currency=USD&viewBy=DURATION', 'flightOffers': 'https://test.api.amadeus.com/v2/shopping/flight-offers?originLocationCode=BOS&destinationLocationCode=SAL&departureDate=2020-05-21&returnDate=2020-05-31&adults=1&nonStop=false&maxPrice=1000&currency=USD'}},
          {'type': 'flight-destination', 'origin': 'BOS', 'destination': 'BOG', 'departureDate': '2020-05-21', 'returnDate': '2020-05-31', 'price': {'total': '620.63'}, 'links': {'flightDates': 'https://test.api.amadeus.com/v1/shopping/flight-dates?origin=BOS&destination=BOG&departureDate=2020-05-21&oneWay=false&duration=10&nonStop=false&maxPrice=1000&currency=USD&viewBy=DURATION', 'flightOffers': 'https://test.api.amadeus.com/v2/shopping/flight-offers?originLocationCode=BOS&destinationLocationCode=BOG&departureDate=2020-05-21&returnDate=2020-05-31&adults=1&nonStop=false&maxPrice=1000&currency=USD'}},
          {'type': 'flight-destination', 'origin': 'BOS', 'destination': 'PUJ', 'departureDate': '2020-05-21', 'returnDate': '2020-05-31', 'price': {'total': '629.23'}, 'links': {'flightDates': 'https://test.api.amadeus.com/v1/shopping/flight-dates?origin=BOS&destination=PUJ&departureDate=2020-05-21&oneWay=false&duration=10&nonStop=false&maxPrice=1000&currency=USD&viewBy=DURATION', 'flightOffers': 'https://test.api.amadeus.com/v2/shopping/flight-offers?originLocationCode=BOS&destinationLocationCode=PUJ&departureDate=2020-05-21&returnDate=2020-05-31&adults=1&nonStop=false&maxPrice=1000&currency=USD'}},
          {'type': 'flight-destination', 'origin': 'BOS', 'destination': 'CPH', 'departureDate': '2020-05-21', 'returnDate': '2020-05-31', 'price': {'total': '647.32'}, 'links': {'flightDates': 'https://test.api.amadeus.com/v1/shopping/flight-dates?origin=BOS&destination=CPH&departureDate=2020-05-21&oneWay=false&duration=10&nonStop=false&maxPrice=1000&currency=USD&viewBy=DURATION', 'flightOffers': 'https://test.api.amadeus.com/v2/shopping/flight-offers?originLocationCode=BOS&destinationLocationCode=CPH&departureDate=2020-05-21&returnDate=2020-05-31&adults=1&nonStop=false&maxPrice=1000&currency=USD'}},
          {'type': 'flight-destination', 'origin': 'BOS', 'destination': 'LON', 'departureDate': '2020-05-21', 'returnDate': '2020-05-31', 'price': {'total': '654.91'}, 'links': {'flightDates': 'https://test.api.amadeus.com/v1/shopping/flight-dates?origin=BOS&destination=LON&departureDate=2020-05-21&oneWay=false&duration=10&nonStop=false&maxPrice=1000&currency=USD&viewBy=DURATION', 'flightOffers': 'https://test.api.amadeus.com/v2/shopping/flight-offers?originLocationCode=BOS&destinationLocationCode=LON&departureDate=2020-05-21&returnDate=2020-05-31&adults=1&nonStop=false&maxPrice=1000&currency=USD'}},
          {'type': 'flight-destination', 'origin': 'BOS', 'destination': 'AUA', 'departureDate': '2020-05-21', 'returnDate': '2020-05-31', 'price': {'total': '661.63'}, 'links': {'flightDates': 'https://test.api.amadeus.com/v1/shopping/flight-dates?origin=BOS&destination=AUA&departureDate=2020-05-21&oneWay=false&duration=10&nonStop=false&maxPrice=1000&currency=USD&viewBy=DURATION', 'flightOffers': 'https://test.api.amadeus.com/v2/shopping/flight-offers?originLocationCode=BOS&destinationLocationCode=AUA&departureDate=2020-05-21&returnDate=2020-05-31&adults=1&nonStop=false&maxPrice=1000&currency=USD'}},
          {'type': 'flight-destination', 'origin': 'BOS', 'destination': 'TGU', 'departureDate': '2020-05-21', 'returnDate': '2020-05-31', 'price': {'total': '662.12'}, 'links': {'flightDates': 'https://test.api.amadeus.com/v1/shopping/flight-dates?origin=BOS&destination=TGU&departureDate=2020-05-21&oneWay=false&duration=10&nonStop=false&maxPrice=1000&currency=USD&viewBy=DURATION', 'flightOffers': 'https://test.api.amadeus.com/v2/shopping/flight-offers?originLocationCode=BOS&destinationLocationCode=TGU&departureDate=2020-05-21&returnDate=2020-05-31&adults=1&nonStop=false&maxPrice=1000&currency=USD'}},
          {'type': 'flight-destination', 'origin': 'BOS', 'destination': 'MBJ', 'departureDate': '2020-05-21', 'returnDate': '2020-05-31', 'price': {'total': '690.67'}, 'links': {'flightDates': 'https://test.api.amadeus.com/v1/shopping/flight-dates?origin=BOS&destination=MBJ&departureDate=2020-05-21&oneWay=false&duration=10&nonStop=false&maxPrice=1000&currency=USD&viewBy=DURATION', 'flightOffers': 'https://test.api.amadeus.com/v2/shopping/flight-offers?originLocationCode=BOS&destinationLocationCode=MBJ&departureDate=2020-05-21&returnDate=2020-05-31&adults=1&nonStop=false&maxPrice=1000&currency=USD'}},
          {'type': 'flight-destination', 'origin': 'BOS', 'destination': 'POS', 'departureDate': '2020-05-21', 'returnDate': '2020-05-31', 'price': {'total': '699.07'}, 'links': {'flightDates': 'https://test.api.amadeus.com/v1/shopping/flight-dates?origin=BOS&destination=POS&departureDate=2020-05-21&oneWay=false&duration=10&nonStop=false&maxPrice=1000&currency=USD&viewBy=DURATION', 'flightOffers': 'https://test.api.amadeus.com/v2/shopping/flight-offers?originLocationCode=BOS&destinationLocationCode=POS&departureDate=2020-05-21&returnDate=2020-05-31&adults=1&nonStop=false&maxPrice=1000&currency=USD'}},
          {'type': 'flight-destination', 'origin': 'BOS', 'destination': 'DEL', 'departureDate': '2020-05-21', 'returnDate': '2020-05-31', 'price': {'total': '759.54'}, 'links': {'flightDates': 'https://test.api.amadeus.com/v1/shopping/flight-dates?origin=BOS&destination=DEL&departureDate=2020-05-21&oneWay=false&duration=10&nonStop=false&maxPrice=1000&currency=USD&viewBy=DURATION', 'flightOffers': 'https://test.api.amadeus.com/v2/shopping/flight-offers?originLocationCode=BOS&destinationLocationCode=DEL&departureDate=2020-05-21&returnDate=2020-05-31&adults=1&nonStop=false&maxPrice=1000&currency=USD'}},
          {'type': 'flight-destination', 'origin': 'BOS', 'destination': 'WRO', 'departureDate': '2020-05-21', 'returnDate': '2020-05-31', 'price': {'total': '841.50'}, 'links': {'flightDates': 'https://test.api.amadeus.com/v1/shopping/flight-dates?origin=BOS&destination=WRO&departureDate=2020-05-21&oneWay=false&duration=10&nonStop=false&maxPrice=1000&currency=USD&viewBy=DURATION', 'flightOffers': 'https://test.api.amadeus.com/v2/shopping/flight-offers?originLocationCode=BOS&destinationLocationCode=WRO&departureDate=2020-05-21&returnDate=2020-05-31&adults=1&nonStop=false&maxPrice=1000&currency=USD'}},
          {'type': 'flight-destination', 'origin': 'BOS', 'destination': 'BHZ', 'departureDate': '2020-05-21', 'returnDate': '2020-05-31', 'price': {'total': '860.43'}, 'links': {'flightDates': 'https://test.api.amadeus.com/v1/shopping/flight-dates?origin=BOS&destination=BHZ&departureDate=2020-05-21&oneWay=false&duration=10&nonStop=false&maxPrice=1000&currency=USD&viewBy=DURATION', 'flightOffers': 'https://test.api.amadeus.com/v2/shopping/flight-offers?originLocationCode=BOS&destinationLocationCode=BHZ&departureDate=2020-05-21&returnDate=2020-05-31&adults=1&nonStop=false&maxPrice=1000&currency=USD'}},
          {'type': 'flight-destination', 'origin': 'BOS', 'destination': 'SNN', 'departureDate': '2020-05-21', 'returnDate': '2020-05-31', 'price': {'total': '868.06'}, 'links': {'flightDates': 'https://test.api.amadeus.com/v1/shopping/flight-dates?origin=BOS&destination=SNN&departureDate=2020-05-21&oneWay=false&duration=10&nonStop=false&maxPrice=1000&currency=USD&viewBy=DURATION', 'flightOffers': 'https://test.api.amadeus.com/v2/shopping/flight-offers?originLocationCode=BOS&destinationLocationCode=SNN&departureDate=2020-05-21&returnDate=2020-05-31&adults=1&nonStop=false&maxPrice=1000&currency=USD'}},
          {'type': 'flight-destination', 'origin': 'BOS', 'destination': 'MAD', 'departureDate': '2020-05-21', 'returnDate': '2020-05-31', 'price': {'total': '913.22'}, 'links': {'flightDates': 'https://test.api.amadeus.com/v1/shopping/flight-dates?origin=BOS&destination=MAD&departureDate=2020-05-21&oneWay=false&duration=10&nonStop=false&maxPrice=1000&currency=USD&viewBy=DURATION', 'flightOffers': 'https://test.api.amadeus.com/v2/shopping/flight-offers?originLocationCode=BOS&destinationLocationCode=MAD&departureDate=2020-05-21&returnDate=2020-05-31&adults=1&nonStop=false&maxPrice=1000&currency=USD'}},
          {'type': 'flight-destination', 'origin': 'BOS', 'destination': 'ALG', 'departureDate': '2020-05-21', 'returnDate': '2020-05-31', 'price': {'total': '953.36'}, 'links': {'flightDates': 'https://test.api.amadeus.com/v1/shopping/flight-dates?origin=BOS&destination=ALG&departureDate=2020-05-21&oneWay=false&duration=10&nonStop=false&maxPrice=1000&currency=USD&viewBy=DURATION', 'flightOffers': 'https://test.api.amadeus.com/v2/shopping/flight-offers?originLocationCode=BOS&destinationLocationCode=ALG&departureDate=2020-05-21&returnDate=2020-05-31&adults=1&nonStop=false&maxPrice=1000&currency=USD'}},
          {'type': 'flight-destination', 'origin': 'BOS', 'destination': 'SOF', 'departureDate': '2020-05-21', 'returnDate': '2020-05-31', 'price': {'total': '982.64'}, 'links': {'flightDates': 'https://test.api.amadeus.com/v1/shopping/flight-dates?origin=BOS&destination=SOF&departureDate=2020-05-21&oneWay=false&duration=10&nonStop=false&maxPrice=1000&currency=USD&viewBy=DURATION', 'flightOffers': 'https://test.api.amadeus.com/v2/shopping/flight-offers?originLocationCode=BOS&destinationLocationCode=SOF&departureDate=2020-05-21&returnDate=2020-05-31&adults=1&nonStop=false&maxPrice=1000&currency=USD'}}],
 'dictionaries': {'currencies': {'USD': 'US DOLLAR'},
                  'locations': {'NAS': {'subType': 'AIRPORT', 'detailedName': 'LYNDEN PINDLING INTL'},
                                'TGU': {'subType': 'AIRPORT', 'detailedName': 'TONCONTIN INTL'},
                                'PUJ': {'subType': 'AIRPORT', 'detailedName': 'INTERNATIONAL'},
                                'BOS': {'subType': 'AIRPORT', 'detailedName': 'EDWARD L LOGAN INTL'},
                                'LON': {'subType': 'CITY', 'detailedName': 'LONDON'},
                                'DEL': {'subType': 'AIRPORT', 'detailedName': 'INDIRA GANDHI INTL'},
                                'SOF': {'subType': 'AIRPORT', 'detailedName': 'SOFIA'},
                                'BZE': {'subType': 'AIRPORT', 'detailedName': 'P.S.W. GOLDSON INTL'},
                                'AUA': {'subType': 'AIRPORT', 'detailedName': 'REINA BEATRIX'},
                                'MAD': {'subType': 'AIRPORT', 'detailedName': 'ADOLFO SUAREZ BARAJAS'},
                                'SNN': {'subType': 'AIRPORT', 'detailedName': 'SHANNON'},
                                'MBJ': {'subType': 'AIRPORT', 'detailedName': 'SANGSTER INTL'},
                                'PTY': {'subType': 'AIRPORT', 'detailedName': 'TOCUMEN INTL'},
                                'POS': {'subType': 'AIRPORT', 'detailedName': 'PIARCO INTL'},
                                'BHZ': {'subType': 'CITY', 'detailedName': 'BELO HORIZONTE'},
                                'WRO': {'subType': 'AIRPORT', 'detailedName': 'NICOLAUS COPERNICUS'},
                                'YTO': {'subType': 'CITY', 'detailedName': 'TORONTO'},
                                'PHL': {'subType': 'AIRPORT', 'detailedName': 'PHILADELPHIA INTL'},
                                'CPH': {'subType': 'AIRPORT', 'detailedName': 'KASTRUP'},
                                'BOG': {'subType': 'AIRPORT', 'detailedName': 'EL DORADO INTL'},
                                'GND': {'subType': 'AIRPORT', 'detailedName': 'MAURICE BISHOP INTL'},
                                'ALG': {'subType': 'AIRPORT', 'detailedName': 'HOUARI BOUMEDIENE'},
                                'BDA': {'subType': 'AIRPORT', 'detailedName': 'L.F WADE INTERNATIONAL'},
                                'SAL': {'subType': 'AIRPORT', 'detailedName': 'EL SALVADOR INTL'}}},
 'meta': {'currency': 'USD', 'links': {'self': 'https://test.api.amadeus.com/v1/shopping/flight-destinations?origin=BOS&departureDate=2020-05-21&oneWay=false&duration=10&nonStop=false&maxPrice=1000&viewBy=COUNTRY'}, 'defaults': {'oneWay': False, 'nonStop': False}}}

countriesDict = {
    "Afghanistan": ["KBL"],
    "Albania": ["TIA"],
    "Algeria": ["AZR","ALG","AAE","BLJ","CBH","BJA","BSK","CZL","DJG","ELU","GHA","HME","IAM","GJL","ORN","OGX", "TMR","TEE","TID","TMX","TIN","TLM"],
    "American Samoa": ["PPG"],
    "Angola": ["LAD"],
    "Anguilla": ["AXA"],
    "Antigua Barbuda": ["ANU"],
    "Argentina": ["ARR","BHI","AEP","EZE","CRD","CTC","COC","COR","CNQ","EHL","EMX","EQS","FMA","GGS","OYA","IGR",
                  "JSM","JUJ","IRJ","ING","LGS","MDQ","MDZ","NQN","PRA","AOL","PMQ","PSS","PRQ","PUD","PMY","RCQ",
                  "RES","RCU","RGL","RGA","ROY","ROS","OES","BRC","UAQ","ULA","LUQ","CPC","AFA","RSA","REL","TUC",
                  "USH","VDM","VLG","VME"],
    "Armenia": ["LWN","EVN"],
    "Aruba": ["AUA"],
    "Australia": ["GET","ADL","ABX","ASP","GYL","ARM","AUU","AYQ","BDD","BNK","ABM","BCI","BHS","BRT","BEU","BVI",
                 "BKQ","BLT","GIC","BOX","BQL","BRK","BMP","BWQ","BNE","BHQ","BME","BDB","BUC","BWT","CNS","CBR",
                 "CVQ","CSI","CED","CTL","CVC","CNJ","CAZ","CNC","CUQ","CFS","CPD","CTN","OOM","CNB","CKI","CMA",
                 "NLF","DRW","DDI","DNM","DRB","DPO","DMD","DBO","DKI","EDR","ELC","EMD","EPR","EXM","FIZ","GPN",
                 "GLT","GLI","OOL","GBL","GOV","GFN","GFF","GTE","HCQ","HTI","HIS","HVB","HBA","HOK","HGD","IVR",
                 "JCK","KAX","KTR","KWM","KUG","LST","LVO","LEA","LER","LNO","LHG","LDC","LSY","LZR","IRG","HAP",
                 "LRE","LDH","UBB","MKY","MNG","MBH","MCV","MKR","MEL","MIM","MQL","MGT","MJK","MOV","MRZ","ONG",
                 "MYA","MGB","MHU","ISA","WME","MMG","DGE","MYI","NAA","NTL","BEO","ZNE","RPM","NTN","NUB","NYN",
                 "OLP","OAG","PBO","PER","PUG","PHE","PLO","PQQ","PTJ","PPP","ULP","RAM","RCM","ROK","RMA","JHQ",
                 "SOI","SYU","MCY","SYD","TMW","TRO","TCA","THG","XTG","TIS","TPR","TWB","TSV","TGN","USL","VCD",
                 "WGA","WGE","WEI","WYA","WUN","WNR","WIN","WUD","WYN","XMY","OKR"],
    "Austria": ["GRZ","INN","LNZ","SZG","VIE"],
    "Azerbaijan": ["GYD","KVD","NAJ"],
    "Bahamas": ["ATC","BIM","NSB","CRI","ELH","FPO","GGT","GHB","IGA","LGI","MAY","MHH","MYG","NAS","ELH","PID","RSD",
               "ZSA","TZN","AXP","SML","TBI","TCB"],
    "Bahrain" : ["BAH"],
    "Bangladesh" : ["BZL","CGP","CXB","JSR","RJH","ZYL","DAC"],
    "Barbados" : ["BGI"],
    "Belarus" : ["MHP","MSQ","VTB"],
    "Belgium" : ["ANR","BRU","LGG","CRL"],
    "Belize" : ["BZE","TZA","CZH","DGA","PLJ","PND"],
    "Benin" : ["COC"],
    "Bermuda" : ["BDA"],
    "Bhutan" : ["PBH"],
    "Bolivia" : ["CIJ","CBB","GYA","LPB","PSZ","RIB","VVI","SRE","TJA","TDD"],
    "Bosnia and Herzegovina" : ["OMO","BNX"],
    "Botswana" : ["FRW","GBE","BBK","MUB"],
    "Brazil" : ["ATM","AJU","ARU","AUX","AAG","BRA","BAU","BEL","PLU","CNF","CNF","BVB","BSB","CPV","CPQ","CGR","CAW",
              "CKS","CAC","CXJ","XAP","CMG","CCM","CZS","CGB","CWB","DOU","FEN","FLN","FOR","FRC","GYN","GVR","IGU",
              "IOS","IMP","IPN","ITB","JCR","JPR","JPA","JOI","JDO","JDF","LAJ","LDB","MCP","MCZ","MAO","MAB","MII",
              "MGF","MEU","MOC","MVS","NAT","NVT","PMW","PHB","PFB","PET","PNZ","PMG","POA","BPS","PVH","PPB","REC",
              "RAO","RBR","GIG","RIG","RVD","SSA","RIA","STM","GEL","CGH","GRU","VCP","SLZ","SOD","TBT","TFF","THE",
              "TOW","TMT","TUR","UBA","UDI","URG","VAG","BVH","VDC"],
    "British Virgin Islands" : ["EIS","TOV","VIJ"],
    "Brunei" : ["BWN"],
    "Bulgaria" : ["BOJ","SOF","VAR"],
    "Burkina Faso" : ["OUA"],
    "Burundi" : ["BJM"],
    "Cambodia" : ["BBM","CYB","PNH","RBE","REP","TNX","DLA","GOV","MVR","NGE","YAO"],
    "Canada" : ["YYC","YEG","YPY","YMM","YQU","YOJ","YQL","YLL","YXH","YPE","YOP","YAZ","YXX","YAA","ZEL","QBC",
              "YPZ","YBL","YCG","YQQ","YCA","YXC","YDQ","DUQ","YPF","YYE","YXJ","YGB","YKA","YLW","YKT","YCD",
              "ZNA","YYF","YPB","YZT","YPW","YXS","YPR","XQU","YQZ","YYD","YXT","CXH","YVR","YWH","YYJ","YWL",
              "YIV","YLC","YBV","YBR","YBT","YYQ","YCR","YDN","YFO","YGX","YGO","ZGI","ILF","XLB","YLR","YNE",
              "YOH","XPK","YRS","ZTM","XSI","YST","ZJN","XTL","YQD","YTD","YTH","YWG","ZAC","ZBF","YFC","YQM",
              "YSJ","YSL","YBI","YRF","YHG","ZUM","YDI","YDF","YFX","YQX","YYR","YHO","YMH","YDP","YHA","YSO",
              "YRG","YYT","YAY","YJT","YWK","YWM","YHZ","YQY","YQI","YCK","YWJ","YGH","YFS","YSM","YHY","YHI",
              "YEV","YSG","YVQ","YPC","YRA","YSY","YFJ","YUB","ZFN","YLE","YZF","YAB","YEK","YBK","YCB","YTE",
              "YCS","YCY","YZS","YHK","YGZ","YUX","YGT","YFB","YBB","YCO","YSR","YXP","YIO","YVM","YRT","YUT",
              "YRB","YSK","YYH","YXN","YAX","YAT","XBE","YTL","XBR","YAC","YLD","XCM","YCC","YVZ","YHD","YFA",
              "YAG","YFH","YER","XGY","YHM","YYU","XKS","ZKE","KEW","YQK","KIF","YGK","YKF","YLH","YXU","YMO",
              "MSA","YQN","YYB","YNO","YOG","YBS","YOO","YOW","YPO","YTA","YPL","YPM","YHP","YRL","ZRJ","ZPB",
              "ZSJ","YZR","YXL","YSH","YCM","YSB","SUR","YQT","YTS","YYZ","YTZ","YWP","YWR","YQG","WNN","AKV",
              "YTF","YPJ","YBG","YBC","YBX","YVB","YHR","YMT","YKU","ZEM","YGP","ZGS","YGV","YGR","YPH","YIK",
              "XGR","YWB","YKG","ZKG","YVP","YGW","YGL","ZLT","YLQ","YYY","YUL","YMX","YMQ","YNA","YNS","YUY",
              "YIF","YPN","YPX","YQC","YQB","XFY","YXK","YRJ","YUY","YZG","YKL","YTQ","YUD","YKQ","YNC","ZFD",
              "YHB","YVC","YNL","YPA","YQR","YXE","YSF","YBE","ZWL","YDA","YOC","YXY","YYG"],
    "Cape Verde" : ["BVC","MMO","RAI","NTO","SNE","VXE"],
    "Cayman Islands" : ["GCM"],
    "Central African Republic" : ["BGF"],
    "Chad" : ["AMO","NDJ"],
    "Chile" : ["ANF","ARI","BBA","CJC","YAI","CCP","CPO","ESR","IQQ","LSC","PMC","PUQ","SCL","ZCO","ZAL"],
    "China" : ["AKU","AAT","AQG","AKA","BPX","BSD","BAV","BHY","PEK","CGQ","CGD","CZX","CHG","CTU","CIF","CKG",
             "DLU","DLC","DAX","DYG","DNH","ENH","FUG","FOC","GOQ","CAN","KWL","KWE","HAK","HLD","HGH","HZG",
             "HRB","HFE","HET","HTN","HYN","JMU","JGN","TNA","JDZ","JHG","JJN","JNZ","JUZ","ZGC","LXA","LYG",
             "LJG","LYI","LZH","LYA","LUM","LZO","MFM","MXZ","MDG","NAO","NKG","NNG","NTG","NNY","NGB","IQM",
             "TAO","NDG","SYX","PVG","SWA","SZX","SYM","TCG","TYN","TSN","TGO","TXN","HLH","URC","WXN","WEH",
             "WNZ","WUH","WUS","XIY","XMN","XFN","XIC","XIL","XNN","XUZ","ENY","YNZ","YNJ","YNT","YBP","YIH",
             "INC","YIN","YIW","UYN","ZHA","ZAT","CGO","HSN","ZUH"],
    "Christmas Island" : ["XCH"],
    "Cocos" : ["CCK"],
    "Colombia" : ["APO","AUC","AXM","BSC","EJA","BAQ","BOG","BGA","CLO","CTG","CAQ","COG","CUC","EYP","FLA","IBE",
                "IPI","LET","MZL","EOH","MDE","MTR","NVA","OTU","PSO","PEI","PBE","UIB","RCH","ADZ","SMR","TCO",
                "VUP"],
    "Comoros" : ["HAH"],
    "Congo" : ["BOA","BZV","FIH","FBM","MDK","MJM","MNB","MAT","NIX","PNR"],
    "Cook" : ["AIT","AIU","MGS","MHX","MUK","MOI","PYE","RAR"],
    "Costa Rica" : ["BCL","RIK","GLF","LIR","NOB","PMZ","PJM","PBP","XQP","SJO","SYQ","TNO","TMU","TTQ"],
    "Cote d'Ivoire" : ["ABJ","GGN"],
    "Croatia" : ["BWK","DBV","OSI","PUY","RJK","SPU","ZAD","ZAG"],
    "Cuba" : ["BCA","BYM","CMW","CYO","AVI","GAO","HAV","HOG","MZO","MOA","GER","VRA"],
    "Cyprus" : ["ECN","LCA","NIC","PFO"],
    "Czech Republic" : ["BRQ","OSR","PRG"],
    "Denmark" : ["AAL","BLL","RNN","BWE","CPH","EBJ","ZBJ","XAK","MJD","ZBQ"],
    "Dijibouti" : ["JIB"],
    "Dominica" : ["DCF","DOM"],
    "Dominican Republic" : ["LRM","POP","PUJ","STI","HEX","SDQ","EPS"],
    "Ecuador" : ["CUE","ESM","GPS","GYE","LGQ","LOH","XMS","MCH","MEC","PVO","UIO","TUA"],
    "Egypt" : ["ABS","AAC","ALY","ATZ","ASW","HBE","CAI","HRG","UVL","LXR","MUH","SSH","TCP"],
    "El Salvador" : ["SAL"],
    "Equatorial Guinea" : ["SSG"],
    "Eritrea" : ["ASM"],
    "Estonia" : ["KDL","TLL"],
    "Ethiopia" : ["AMH","BJR","BEI","DBM","DBT","DEM","DSE","DIR","GMB","GOB","GDQ","GOR","JIJ","JIM","BCO","ABK",
                "LLI","MQX","MKS","NDM","MTF","EGL","HIL","TIE","TUJ","ADD","ASO","GDE"],
    "Falkland Islands" : ["MPN","PSY"],
    "Faroe Islands" : ["FAE"],
    "Fiji" : ["LEV","CST","ICI","LBS","LKB","LUC","PTF","MNF","MFJ","NAN","NGI","SVU","SUV","TVU","VBV"],
    "Finland" : ["ENF","HEL","IVL","JOE","JYV","KAJ","KTT","KUO","KAO","LPP","MHQ","MIK","OUL","POR","RVN","SVL",
               "TMP","TKU","VAA","VRK"],
    "France" : ["AGF","AJA","ANE","ANG","NCY","AUR","AVN","BIA","EGC","BZR","BIQ","BOD","BES","CFR","CLY","JCA",
              "CEQ","QYW","CCF","DCM","CMF","CFE","DOL","DIJ","DNR","EPL","FSC","GNB","LAI","LRH","LEH","ZLN",
              "LPY","LTQ","LIL","LIG","LRT","LDE","XYD","LYS","MRS","ETZ","MPL","MLH","NTE","NCE","FNI","BVA",
              "CDG","ORY","PAR","PUF","PGX","PGF","PIS","UIP","RNS","RNE","RDZ","URO","LTT","XPZ","EBU","SXB",
              "TLN","TLS","TUF","XVS"],
    "French Guiana" : ["CAY"],
    "French Polynesia" : ["AUQ","BOB","FAV","HUH","HUU","XMH","MAU","MOZ","NHV","PPT","RFP","RUR","TIH","TUB"],
    "Gabon" : ["MVB","GAX","LBV","MKU","MFF","MJL","OMB","OYE","POG","RHO","TCH"],
    "Georgia" : ["BJL","BUS","KUT","TBS"],
    "Germany" : ["AGB","BYU","SXF","TXL","THF","BER","BNJ","BMK","BRE","CGN","DTM","DRS","DUS","MGL","EIB","ERF",
               "XFW","FLF","HHN","FRA","FDH","ZHQ","HAM","LBC","HAJ","HDB","HGL","HDF","HOQ","JUI","FKB","LEJ",
               "MHG","FMO","MUC","NRD","NDZ","NUE","PAD","RLG","QFZ","STR","AGE","GWT","WVN"],
    "Ghana" : ["ACC"],
    "Gibraltar" : ["GIB"],
    "Greece" : ["AXD","ATH","CHQ","HER","IOA","AOK","KVA","EFL","CFU","LXS","JMK","MJT","GPA","PVK","SMI","JSI",
              "SKG","JTR","ZTH"],
    "Greenland" : ["UMD","JEG","JGR","JAV","KUS","JSU","JNN","JNS","UAK","CNP","GOH","JFR","THU","JJU","JHS","JUV"],
    "Grenada" : ["GND"],
    "Guatemala" : ["FRS","GUA"],
    "Guiana" : ["OXB","CKY","LHW"],
    "Guyana" : ["GEO"],
    "Haiti" : ["CAP","PAP"],
    "Honduras" : ["BHG","GJA","LCE","PCH","PEU","RTB","SAP","TGU","TJI","UII"],
    "Hong Kong" : ["HKG"],
    "Hungary" : ["BUD"],
    "Iceland" : ["AEY","EGS","GRY","HFN","IFJ","KEF","RPN","THO","VEY","VPN"],
    "India" : ["IXA","AGR","AMD","AJL","ATQ","IXU","IXB","BLR","BHU","BHO","BBI","BHJ","BOM","CCU","IXC","MAA",
             "COK","CJB","DEL","DIB","DMU","DIU","GAU","GOI","GWL","HYD","IMF","IDR","JAI","JGA","JDH","IXJ",
             "JRH","HJR","CCU","CCJ","IXL","LKO","IXM","IXE","BOM","NAG","PAT","PBD","IXZ","PNQ","PUT","RAJ",
             "IXR","IXS","SXR","TEZ","TRV","TRZ","TIR","UDR","BDQ","VNS","VTZ"],
    "Indonesia" : ["OKQ","ARD","AMQ","AGD","AYW","BXB","BXD","BPN","BTJ","TKG","BDO","BDJ","BTH","BXM","BKS","BEJ",
                 "BIK","BMU","NTI","BUI","DRH","DTD","DPS","DIL","DOB","DUM","EWI","ENE","EWE","FKQ","GEB","GTO",
                 "ILA","IUL","INX","CGK","DJJ","KBX","KCD","KBF","KDI","LBJ","LUV","LKA","LPU","LBW","LUW","MDC",
                 "MKW","AMI","MOF","MES","MKQ","RDE","MDP","ONI","LII","NBX","NNX","OBD","OKL","PDG","PKY","PLM",
                 "PLW","PKN","PGK","PKU","PNK","PSU","ZRM","SXK","SRG","ZEG","ZRI","NKD","SQG","SOC","SUB","TMC",
                 "TMH","TJQ","TJS","TRK","TIM","TXM","TTE","UPG","WET","WBA","WGP","WMX","WSR","JOG","UGU"],
    "Iran" : ["ABD","AWZ","ADU","BXR","BND","BDH","BUZ","BJB","ZBR","IFN","MHD","RJN","RAS","SYZ","TBZ","THR","OMH",
            "AZD","ZAH"],
    "Ireland" : ["ORK","CFN","DUB","GWY","NOC","SNN","SXL","WAT"],
    "Israel" : ["HFA","VDA","TLV"],
    "Italy" : ["AHO","AOI","AOT","BRI","BZO","BDS","CAG","CTA","CRV","ETH","EBA","PSA","FLR","FOG","GOA","SUF","LMP",
            "LIN","MXP","BGY","PMF","NAP","OLB","PMO","PNL","PMF","PEG","PSR","PSA","REG","RMI","CIA","FCO","ROM",
            "TAR","TTB","TPS","TRS","TRN","VCE","TSF","VRN"],
    "Jamaica" : ["KIN","KTP","MBJ","NEG","OCJ","POT"],
    "Japan" : ["AGJ","AXT","ASJ","AOJ","AKJ","FUJ","FUK","FKS","HAC","HKD","HTR","HIW","HIJ","ISG","IWJ","IZO","KTD",
             "KCZ","UEO","KUH","MMJ","MYJ","MMB","MMD","MSJ","MYE","MMY","MBE","HNA","NGS","NGO","NGO","OBO","OIT",
             "OKJ","OKA","OIR","ITM","KIX","OSA","OIM","RBJ","RIS","CTS","OKD","SYO","TRA","TKN","TKS","HND","NRT",
             "TYO","TTJ","TOY","TSJ","UBJ","WKJ","GAJ","YGJ","OGN","RNJ"],
    "Jordan" : ["ADJ","AMM","AQJ"],
    "Kazakhstan" : ["AKX","AKX","TSE","GUW","PWQ","CIT","URA","UKK"],
    "Kenya" : ["ASV","EDL","KWY","LAU","MYD","MRE","MBA","NBO","WIL","NYK","UAS"],
    "Kiribati" : ["TRW"],
    "Kuwait" : ["KWI"],
    "Kyrgyzstan" : ["FRU"],
    "Laos" : ["HOE","LXG","LPQ","ODY","PKZ","ZVK","ZBY","VTE","XKH"],
    "Latvia" : ["RIX"],
    "Lebanon" : ["BEY"],
    "Lesotho" : ["MSU"],
    "Liberia" : ["ROB"],
    "Libya" : ["LAQ","BEN","BCQ","LTD","GHT","HUQ","AKF","MRA","TOB","TIP"],
    "Lithuania" : ["KUN","PLQ","VNO"],
    "Luxembourg" : ["LUX"],
    "Macedonia" : ["OHD","SKP"],
    "Madagascar" : ["WTA","IVA","AMY","WAM","HVA","JVA","ANM","WAQ","DIE","WAI","BMD","BPY","RVA","WFI","FTU","VVB",
                  "MXT","MJN","WMP","WVK","WMR","MNJ","WMA","MJA","WMN","ZVA","TVA","MXM","MOQ","NOS","WPB","SVB",
                  "SMS","DWB","TMM","TTS","WTS","TLE","VAT","VOH","TNR"],
    "Malawi" : ["BLZ","CMK","LLW","ZZU"],
    "Malaysia" : ["AOR","BBN","BTU","BKZ","IPH","JHB","KBR","BKI","KUL","TGG","KUA","KCH","KUD","LBU","LDU","LGK",
                "LWY","LMN","LBP","LGL","ODN","MKZ","MUR","MYY","MKM","MZV","PEN","TWU","TOD","TMG"],
    "Maldives" : ["GAN","HAQ","KDM","KDO","MLE"],
    "Mali" : ["BKO","GUD","MZI","TOM","EYL"],
    "Malta" : ["GZM","MLA"],
    "Marshall" : ["AIM","AIC","AUL","BII","EBO","ENT","JAT","UIT","JEJ","KBT","KWA","LML","LIK","LOF","MJE","MAJ",
                "MAV","MJB","MIJ","NDK","RNP","UJE","UTK","WJA","WTO","WTE"],
    "Martinique" : ["FDF"],
    "Mauritania" : ["AEO","EMN","NDB","NKC","TIY","OUZ"],
    "Mauritius" : ["MRU","RRG"],
    "Mayotte" : ["DZA"],
    "Mexico" : ["ACA","AGU","SJD","CPE","CUN","CTM","CUU","CME","CJS","CEN","CVM","CLQ","CZM","CVJ","CUL","DGO",
              "GDL","BJX","GYM","GUB","HMO","HUX","ZIH","IZT","JAL","LAP","BJX","LTO","SJD","LMM","LZC","ZLO",
              "MAM","MZT","MID","MXL","MEX","MTT","LOV","MTY","MLM","NLD","OAX","PQM","PDS","PAZ","PBC","PXM",
              "PVR","QRO","REX","SZT","SLW","SLP","TAM","TAP","TPQ","TIJ","TLC","TRC","TGZ","UPN","VER","VSA",
              "ZIH"],
    "Micronesia" : ["PNI","TKK","ULI","YAP"],
    "Monaco" : ["MCM"],
    "Mongolia" : ["ULN","ULY"],
    "Montserrat" : ["MNI"],
    "Montserrat" : ["AGA","AHU","CAS","CMN","VIL","FEZ","EUN","NDR","OZZ","OUD","RBA","TNG","TTU"],
    "Mozambique" : ["BEW","BLG","VXC","MPM","MNC","APL","POL","UEL","TET","VNX"],
    "Myanmar" : ["BMO","TVY","HEH","KAW","MDL","MNU","MGZ","MYT","NYU","AKY","THL","SNW","RGN"],
    "Namibia" : ["LUD","OKU","MPA","OND","OMD","SZM","TSB","WVB"],
    "Nauru" : ["INU"],
    "Nepal" : ["BDP","BWA","BHR","BIR","JKR","JMO","KTM","LUA","NGX","PKR"],
    "Netherlands" : ["AMS","EIN","GRQ","MST","RTM"],
    "Netherlands Antilles" : ["BON","CUR","SXM","EUX"],
    "New Caledonia" : ["BMY","ILP","LIF","MEE","GEA","NOU","UVE","TGJ","TOU"],
    "New Zealand" : ["AKL","BHE","CHT","CHC","DUD","GIS","HLZ","HKK","IVC","KAT","MON","NSN","NPL","PMR","ZQN","ROT","TUO",
          "TRG","TEU","TIU","WKA","WAG","WLG","WSZ","WHK","WRE"],
    "Nicaragua" : ["MGA"],
    "Niger" : ["NIM"],
    "Nigeria" : ["ABV","CBQ","ENU","KAN","LOS","PHC"],
    "Niue" : ["IUE"],
    "Norfolk" : ["NLK"],
    "North Korea" : ["FNJ"],
    "Northern Mariana" : ["ROP","SPN","TIQ"],
    "Norway" : ["AES","ALF","ANX","BDU","BJF","BGO","BVG","BOO","BNN","VDB","FRO","FDE","HFT","HAA","HAU","HVG",
              "LKL","LKN","MEH","MQN","MOL","MJF","OSY","NVK","OSL","RVK","ZXM","RRS","RET","QFK","SOG","SOJ",
              "SVG","SVJ","TRF","TOS","TRD","VDS","VAW"],
    "Oman" : ["MCT"],
    "Pakistan" : ["BHV","BNP","CJL","DEA","DSK","LYP","GIL","GWD","ISB","JAG","JIW","KCF","KHI","KDD","LHE","MUX",
                "MFG","WNS","ORW","PJG","PAJ","PSI","PEW","UET","RAZ","SUL","TUK","PZH"],
    "Palau" : ["ROR"],
    "Palesrine" : ["GZA"],
    "Panama" : ["BFQ","BOC","CHX","CTD","ONX","OTD","DAV","ELE","GHE","JQE","PLP","PAC","PTY","NMG"],
    "Papua New Guinea" : ["CMU","AUP","GUR","AZB","ARP","VMU","OPU","BOV","BUA","BXZ","CPI","CVL","DAU","DER","DDM","EMS","EMO",
           "GAR","GRL","GOE","GKA","HIT","HKN","IHU","IDN","IOP","ITK","JAQ","KBM","KZF","KUY","KVG","UNG","KUQ",
           "LAB","LAE","LNV","LSA","MAG","MFO","MAS","MDU","MYX","MIS","MXH","HGU","ATN","NDI","PNP","POM","RBP",
           "RAB","SWG","TBG","TIZ","TKB","TDB","TFI","URU","VAI","VIV","AGL","WSU","WUG","WED","WWK","KYX"],
    "Paraguay" : ["ASU","AGT"],
    "Peru" : ["AQP","CJA","CIX","CUZ","IQT","JUL","LIM","PIU","PCL","PEM","TCQ","TPP","TRU","TBP"],
    "Philippines" : ["DVO","BCD","BSO","BXU","CGY","CEB","CBO","DPL","DGT","GES","ILO","IPE","LAO","LGP","MNL",
                   "MBT","WNP","PPS","TAC","TUG","ZAM"],
    "Poland" : ["BZG","GDN","KTW","QJY","OSZ","KRK","POZ","SZZ","WAW","WRO","IEG"],
    "Portugal" : ["CVU","FAO","FLW","FNC","GRW","HOR","LIS","PIX","PDL","OPO","PXO","SMA","TER"],
    "Puerto Rico" : ["BQN","FAJ","MAZ","PSE","PSE","SJU","SJU","VQS"],
    "Qatar" : ["DOH"],
    "Romania" : ["ARW","BAY","BBU","OTP","CLJ","CND","IAS","OMR","SUJ","TSR","TGM"],
    "Russia" : ["ABA","AER","AMV","DYR","AAQ","ARH","ASF","BAX","EGO","BQS","BTK","UUA","UUA","CSY","CEK","CEE",
              "CEE","HTA","SVX","ESL","GDZ","IAA","INA","IKT","KGD","KZN","KXK","KYZ","GDX","MQF","MCX","MRV",
              "MJZ","BKA","DME","SVO","VKO","MOW","MMK","NYM","NAL","NNM","NUX","NFG","NER","NJC","GOJ","NOJ",
              "NSK","NVR","NOZ","OVB","OHO","OMS","REN","OSW","PEX","PEE","PKC","PES","PYJ","RAT","ROV","LED",
              "SLY","KUF","RTW","LED","STW","IKS","TOF","TJM","UFA","UCT","UUD","URJ","USK","UIK","OGZ","VVO",
              "VLK","VOG","VKT","VOZ","YKS","IAR","UUS"],
    "Rwanda" : ["KGL"],
    "Saint Vince" : ["CIW","SVD"],
    "Saudi Arabia" : ["AHB","ABT","RAE","BHH","DMM","ELQ","GIZ","URY","HAS","HOF","JED","AJF","MED","EAM","AQI","RAH",
             "RUH","TUU","TIF","TUI","WAE","EJH","YNB"],
    "Senegal" : ["DKR"],
    "Sierra Leone" : ["FNA"],
    "Singapore" : ["SIN","XSP"],
    "Slovakia" : ["BTS","TAT"],
    "Slovenia" : ["LJU","MBX"],
    "Solomon" : ["AFT","ATD","AKS","BAS","BPF","BNY","CHY","FRE","GZO","HIR","IRA","MNY",
               "MUA","PRS","RBV","RNL","NNB","EGM","VAO","XYA"],
    "Somalia" : ["BBO","BSA","BUO","MGQ","HGA"],
    "South Africa" : ["ALJ","BFN","CPT","DUR","ELS","GRJ","HDS","JNB","MGH","NLP","PHW","PZB","PTG","PBZ","PLZ",
                   "RCB","SZK","NTY","ULD","UTT","UTN"],
    "South Korea" : ["PUS","CJJ","TAE","KAG","KUV","KWJ","CJU","HIN","MPK","GMP","ICN","SEL","USN","WJU","RSU"],
    "Spain" : ["ALC","LEI","BJZ","BCN","BIO","FUE","GRO","GRX","IBZ","XRY","LCG","ACE","LPA","MAD","AGP","MLN",
             "MAH","MJV","PNA","FUE","EAS","VLC","VGO"],
    "Canary Islands" : ["OVD","JCU","PMI","REU","SPC","SVQ","TFN","VLL","VDE","VIT","ZAZ","TFS"],
    "Sri Lanka" : ["CMB"],
    "Sudan" : ["DOG","ELF","EBD","EGN","MAK","MWE","UYL","PZU","WHF","WUU"],
    "Suriname" : ["PBM","ORG"],
    "Sweden" : ["JHE","AGH","AJR","BLE","GEV","GOT","GSE","HFS","HAD","HMV","HUV","HLF","JKG","LPI","LLA","LYC",
              "MMX","MXX","NRK","OER","OSK","OSD","RNB","KVB","SOO","ARN","BMA","STO","SQO","EVG","TYF","THN",
              "UME","VST","VXO","VHM","VBY","ORB"],
    "Switzerland" : ["ACH","BSL","ZDH","BRN","GVA","LUG","ZRH"],
    "Syria" : ["DEZ","LTK","ALP","DAM","KAC"],
    "Taiwan" : ["CMJ","CYI","HUN","MZG","PIF","TXG","TNN","TPE","TSA","TTT","WOT"],
    "Tajikistan" : ["DYU","LBD"],
    "Tanzania" : ["ARK","DAR","DOD","TKQ","JRO","LDI","MFA","MYW","MUZ","MWZ","PMA","TBO","ZNZ"],
    "Thailand" : ["BKK","BFV","CNX","CEI","HDY","HHQ","USM","KBV","LPI","HGN","MAQ","NAK","NST","NNT","NAW","PHS",
                "PRH","HKT","UNN","SNO","THS","URT","TST","UBP","UTH","UTP"],
    "Trinisia" : ["POS","TAB"],
    "Tunisia" : ["DJE","GAF","MIR","TBJ","TOE","TUN"],
    "Turkey" : ["ADA","AJI","ESB","ANK","AYT","BZI","BAL","BJV","DLM","DNZ","DIY","EDO","EZS","ERC","ERZ","GZT",
              "IST","ADB","KCM","ASR","KYA","MLX","MSR","VAS","TZX","VAN"],
    "Virgin Islands" : ["STX","STT","STX","STT"],
    "Uganda" : ["RUA","EBB","ULU","JIN","VSG","PAF"],
    "Ukraine" : ["DNK","DOK","IFO","HRK","KBP","IEV","KWG","LWO","MPW","ODS","PLV","UDJ","OZH"],
    "United Arab Emirates" : ["AUH","FJR","AAN","DXB","RKT"],
    "United Kingdom" : ["ABZ","ACI","BRR","BFS","BHD","BEB","BHX","BLK","BOH","BRS","CBG","CAL","CWL","CEG","DND","EOI","EDI",
          "EXT","FIE","FZO","GLA","PIK","GCI","HUY","INV","ILY","IOM","ISC","TSO","JER","LEQ","LBA","LPL","BQH",
          "LGW","LHR","LCY","LTN","STN","QQP","LON","LDY","MAN","MSE","NCL","NQY","NRL","NWI","EMA","PPW","PZE",
          "PLH","NDY","SZD","LWK","LSI","SOU","SYY","SOY","MME","TRE","WRY","WIC"],
    "United States" : ["ADK","KKI","AKI","KQA","AUK","WKK","AET","ABL","AKP","ANC","AGN","ANI","ANV","ARC","AKB","ATK","BRW",
          "BTI","WBQ","BET","BTT","KBC","BYA","RBH","BKC","LUR","EHM","CEM","CIK","CYF","VAK","CKX","KCQ","KCG",
          "KCL","CZN","CHU","IRC","CHP","CLP","CFA","KCC","CDB","CDV","CGA","CKO","CUW","DRG","DJN","DLG","DUT",
          "EDA","EEK","KKU","KEK","ELV","ELI","EMK","FAI","GLV","GNU","KGX","GST","HNS","HKB","HYL","HCR","HOM",
          "HNH","HPB","HUS","HSL","HYG","IGG","ILI","JNU","KAE","KNK","KLG","KAL","KXA","KUK","ENA","KTN","IAN",
          "KVC","AKN","KPN","KVL","KLW","OBU","ADQ","KKH","KOT","OTZ","KYU","KWT","KWK","LMA","KLL","MLY","KMO",
          "MLL","MCG","MYU","MTM","WMK","MNT","MOU","WNA","PKA","NKI","NLG","NCN","KGK","KNW","WWT","NME","NIB",
          "IKO","WTK","OME","NNL","ORV","ORT","NUI","NUL","NUP","PDB","PEC","KPV","PSG","UGB","PIP","PQS","PTU",
          "KPB","PHO","PIZ","PTA","KPC","PTH","PML","PPV","PCA","SCC","KWN","RMP","RDV","RBY","RSH","STG","KSM",
          "SMK","SNP","SDP","SVA","SCM","WLK","SWD","SHX","SKK","SXP","SHH","SHG","SIT","SGY","SLQ","WSN","WBB",
          "SVS","SRV","TCT","TKA","TAL","TEK","KTS","TKE","TEH","KTB","TNC","TOG","TKJ","OOK","TLT","WTL","TNK",
          "TWA","UNK","UTO","VDZ","VEE","AIN","WAA","KWF","WWP","WMO","WRG","YAK","BHM","DHN","MSL","HSV","MOB",
          "MGM","MSL","MSL","TCL","WAS","ELD","FYV","XNA","FSM","HRO","HOT","JBR","LIT","WMH","TXK","IFP","FLG",
          "JGC","GCN","HAE","IGM","HII","PGA","PHX","PRC","TUS","YUM","ACV","BFL","BUR","CLD","MRY","CIC","CCR",
          "CEC","IPL","ACV","FAT","IPL","IYK","LGB","LAX","MCE","MOD","MRY","OAK","ONT","SNA","OXR","PSP","RDD",
          "SMF","SAN","SFO","SJC","SBP","SNA","SBA","SMX","STS","SCK","OXR","VIS","ALS","ASE","WHH","WBU","COS",
          "CEZ","DEN","DRO","FNL","GJT","GUC","HDN","FNL","MTJ","PUB","SBS","TEX","EGE","GON","BDL","HVN","BDL",
          "PIE","DAB","FLL","RSW","VPS","GNV","JAX","EYW","MLB","MIA","MPB","APF","ORL","MCO","PFN","PNS","SFB",
          "SRQ","PIE","TLH","TPA","VPS","PBI","AHN","ATL","AGS","BQK","CSG","MCN","SAV","VLD","HNM","PAK","ITO",
          "HNL","MKK","OGG","LUP","MUE","JHM","LIH","KOA","LNY","LIH","OGG","BRL","CID","DSM","DBQ","FOD","MCW",
          "OTM","SUX","ALO","BOI","SUN","IDA","LWS","PIH","SUN","TWF","BLV","BMI","MDH","CMI","MDW","ORD","CHI",
          "DEC","MWA","MLI","PIA","UIN","ZRF","ZRK","SPI","CMI","EVV","FWA","GYY","IND","LAF","SBN","HUF","CNK",
          "DDC","GCK","HYS","LBL","MHK","SLN","FOE","ICT","BWG","LEX","SDF","OWB","PAH","HTS","AEX","BTR","LFT",
          "LCH","MLU","MSY","SHV","BED","BOS","HYA","MVY","ACK","PVC","ORH","BWI","CBE","HGR","AUG","BGR","BHB",
          "PWM","PQI","RKD","CIU","APN","MBS","BEH","DTW","DTT","ESC","FNT","GRR","CMX","IMT","IWD","AZO","LAN",
          "MBL","MQT","MBS","MKG","PLN","MBS","TVC","BJI","BRD","HIB","DLH","LYU","GPZ","HIB","INL","MKT","MSP",
          "RST","STC","TVF","CGI","COU","TBN","JLN","MCI","IRK","STL","SGF","GPT","GTR","GLH","GPT","JAN","PIB",
          "MEI","TUP","BIL","BZN","BTM","GGW","GDV","GTF","HVR","HLN","LWT","MLS","MSO","WYS","AVL","CLT","RDU",
          "RDU","FAY","GSO","PGV","AVL","HKY","GSO","OAJ","RDU","SOP","ILM","BIS","DVL","DIK","FAR","GFK","JMS",
          "MOT","ISN","AIA","CDR","GRI","EAR","LNK","MCK","OFK","LBF","OMA","BFF","LEB","EEN","LEB","MHT","PSM",
          "AIY","EWR","TTN","ALM","ABQ","CNM","CVN","FMN","GUP","HBB","ROW","SAF","SVC","TSM","EKO","EUE","LAS",
          "RNO","ALB","BGM","BUF","ELM","BGM","ISP","ITH","JHW","BGM","MSS","JFK","LGA","NYC","SWF","OGS","PLB",
          "POU","ROC","SLK","SWF","SYR","UCA","ART","HPN","CAK","CAK","CVG","CLE","CMH","DAY","TOL","YNG","PKB",
          "WDG","LAW","OKC","PNC","TUL","EUG","LMT","MDJ","MFR","OTH","PDT","PDX","RDM","SLE","ABE","AOO","ABE",
          "BFD","DUJ","ABE","ERI","FKL","MDT","JST","LNS","LBE","AOO","PHL","TTN","PIT","RDG","AVP","SCE","AVP",
          "IPT","BID","PVD","WST","CHS","CAE","FLO","GSP","HHH","MYR","GSP","ABR","BKX","HON","PIR","RAP","FSD",
          "ATY","CHA","MKL","TRI","TRI","TYS","MEM","BNA","ABI","AMA","AUS","BPT","BWD","BRO","CLL","CRP","DFW",
          "DAL","DRT","ELP","DFW","GGG","HRL","HOU","IAH","HOU","GGG","ILE","LRD","GGG","LBB","MFE","MAF","MFE",
          "MAF","BPT","SJT","SAT","TYR","VCT","ACT","SPS","JON","MDY","CDC","CNY","SGU","SLC","VEL","TRI","CHO",
          "PHF","PHF","ORF","RIC","ROA","SHD","PHF","BTV","RUT","LEB","BLI","LPS","MWH","PSC","CLM","PUW","RCE",
          "RSJ","LKE","SEA","GEG","ALW","EAT","WSX","YKM","RHI","ATW","EAU","GRB","JVL","LSE","MSN","MKE","OSH",
          "CWA","CWA","BKW","BLF","CRW","CKB","LWB","MGW","BLF","HTS","PKB","CPR","CYS","COD","GCC","JAC","LAR",
          "RIW","RKS","SHR","WRL","COD"],
    "Uruguay" : ["MVD","PDP"],
    "Uzbekistan" : ["AZN","BHK","FEG","NMA","NCU","TAS","TMJ","UGC"],
    "Vanuatu" : ["DLY","EAE","AUY","AWD","CCV","SON","FTA","ZGU","IPA","LPM","LNB","LOD","LNE","MWF","MTV","NUS",
               "OLJ","PBJ","VLI","SSR","TAH","TGH","TOH","ULB","VLS","WLH"],
    "Venezuela" : ["AGV","BLA","BNS","BRM","CAS","CCS","CUP","CBL","CZE","CUM","VIG","GUI","LSP","MAR","MYC","MUN",
                 "MRD","PMV","PYH","PZO","SVZ","STB","STD","TUV","VLN","VLV"],
    "Vietnam" : ["BMV","DAD","DIN","HPH","HAN","SGN","HUI","NHA","PQC","PXU","UIH","VKG","VKG","SQH","VII"],
    "Western Samoa" : ["APW","FGI","MXS"],
    "Yemen" : ["ADE","AAY","AXK","HOD","RIY","SAH","GXF","TAI"],
    "Zambia" : ["CIP","ZKB","KAA","LVI","LUN","MNR","MFU","NLA"],
    "Zimbabwe" : ["BUQ","HRE","HWN","KAB","VFA"]}

currenciesDict = {
    "AED": ["United Arab Emirates"],
    "ANG": ["Curaçao", "Sint Maarten"],
    "AOA": ["Angola"],
    "ARS": ["Argentina"],
    "AUD": ["Australia", "Kiribati", "Nauru", "Tuvalu"],
    "AWG": ["Aruba"],
    "BBD": ["Barbados"],
    "BGN": ["Bulgaria"],
    "BMD": ["Bermuda"],
    "BND": ["Brunei", "Singapore"],
    "BOB": ["Bolivia"],
    "BRL": ["Brazil"],
    "BSD": ["Bahamas", "The Bahamas"],
    "BYN": ["Belarus"],
    "BZD": ["Belize"],
    "CAD": ["Canada"],
    "CHF": ["Switzerland"],
    "CLP": ["Chile"],
    "CNY": ["China"],
    "COP": ["Colombia"],
    "CRC": ["Costa Rica"],
    "CUP": ["Cuba"],
    "DKK": ["Denmark"],
    "DOP": ["Dominican Republic"],
    "EGP": ["Egypt"],
    "ETB": ["Ethiopia"],
    "EUR": ["Andorra", "Austria", "Belgium", "Estonia", "Finland", "France", "Germany", "Greece", "Ireland", "Italy",
            "Latvia", "Lithuania", "Luxembourg", "Netherlands", "Portugal", "Slovakia", "Slovenia", "Spain", "Vatican City"],
    "GBP": ["Alderney", "Guernsey", "Isle of Man", "Jersey", "United Kingdom", "UK"],
    "HKD": ["Hong Kong"],
    "HUF": ["Hungary"],
    "IDR": ["Indonesia"],
    "ISL": ["Israel", "Palestine"],
    "INR": ["Bhutan", "India"],
    "IQD": ["Iraq"],
    "IRR": ["Iran"],
    "ISK": ["Iceland"],
    "JMD": ["Jamaica"],
    "JPY": ["Japan"],
    "KRW": ["South Korea"],
    "KYD": ["Cayman Islands"],
    "LBP": ["Lebanon"],
    "MVR": ["Maldives"],
    "MXN": ["Mexico"],
    "NIO": ["Nicaragua"],
    "NOK": ["Norway"],
    "NZD": ["New Zealand", "Cook Islands", "Niue", "Pitcairn Islands"],
    "PAB": ["Panama"],
    "PEN": ["Peru"],
    "PHP": ["Philippines"],
    "PLN": ["Poland"],
    "PYG": ["Paraguay"],
    "RON": ["Romania"],
    "RSD": ["Serbia"],
    "RUB": ["Russia", "Ukraine"],
    "RWF": ["Rwanda"],
    "SEK": ["Sweden"],
    "SGD": ["Singapore"],
    "SYP": ["Syria"],
    "TRY": ["Turkey"],
    "UAH": ["Ukraine"],
    "USD": ["United States", "US", "British Vigin Islands", "Ecuador", "El Salvador", "Marshall Islands", "Panama"],
    "UYU": ["Uruguay"],
    "VES": ["Venezuela"],
    "VND": ["Vietnam"],
    "YER": ["Yemen"],
    "ZAR": ["Eswatini", "Namibia", "South Africa"]
}

def main_func(response):
    final = [["Origin", "Airport", "Country of Destination", "Departure Date", "Return Date", "Flight price", "Currency"]]

    for i in range(len(response["data"])):
        line = []
        origin = [response["data"][i]["origin"]]
        dest = [response["data"][i]["destination"]]
        airport = [response["dictionaries"]["locations"][dest[0]]["detailedName"]]
        cnt = country(dest[0])
        departure_date = [response["data"][i]["departureDate"]]
        return_date = [response["data"][i]["returnDate"]]
        flight_price = [response["data"][i]["price"]["total"]]

        origin_currency = [response["meta"]["currency"]]

        line += origin
        line += airport
        line += [cnt]
        line += departure_date
        line += return_date
        line += flight_price

        currency = finding_currency2(origin_currency, cnt)
        line += [currency]
        final += [line]

    for i in final:
        print(i)

def finding_currency2(currency_origin, country_destination):
    # need to find currency for the destination country
    currency_destination = curr(country_destination)
    try:
        api_call = "https://prime.exchangerate-api.com/v5/248168ed348d212c46b7400e/latest/"
        api_call += currency_origin[0]
        response = requests.get("https://prime.exchangerate-api.com/v5/248168ed348d212c46b7400e/latest/USD")
        currency = response.json()["conversion_rates"][currency_destination]
        return currency
    except KeyError:
        return "Currency not found"

def country(airport):
    for key, values in countriesDict.items():
        for value in values:
            if value == airport:
                return key

def curr(country):
    for key, values in currenciesDict.items():
        for value in values:
            if value == country:
                return key
    return ""

main_func(APIresponse)